.PHONY: clean All

All:
	@echo "----------Building project:[ Sec_6_factorial_recursion - Debug ]----------"
	@cd "Sec_6_factorial_recursion" && "$(MAKE)" -f  "Sec_6_factorial_recursion.mk"
clean:
	@echo "----------Cleaning project:[ Sec_6_factorial_recursion - Debug ]----------"
	@cd "Sec_6_factorial_recursion" && "$(MAKE)" -f  "Sec_6_factorial_recursion.mk" clean
